# Generated by Django 5.2.11 on 2026-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='location_type',
            field=models.CharField(choices=[('within', 'Within Bayawan City'), ('outside', 'Outside')], default='within', max_length=20),
        ),
    ]
