# Generated by Django 5.2.11 on 2026-02-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
